import type { Lang } from "./zones";

/** Textos propios de la página pública, en los dos idiomas que ofrece al visitante. */
export const T = {
  es: {
    allServices: "Todos los servicios",
    minutes: (n: number) => `${n} min`,
    location: { in_person: "Presencial", phone: "Llamada telefónica", video: "Videollamada", custom: "Otro lugar" } as Record<string, string>,
    yourZone: "Tu zona horaria",
    detected: "Detectada en tu dispositivo.",
    chosen: "Elegida por ti.",
    bizZone: (name: string, label: string) => `${name} atiende en hora de ${label}.`,
    searchZone: "Busca una ciudad o una zona",
    zoneGroupMine: "Tu zona",
    allZones: (n: number) => `Todas las zonas · ${n}`,
    noResults: "Sin resultados",
    confirmed: "Cita confirmada",
    sameInBiz: (name: string) => `La misma cita en la zona de ${name}:`,
    emailSent: "Te hemos enviado un correo con los detalles y los enlaces para cambiarla o cancelarla.",
    rescheduleEyebrow: "Cambiar tu cita",
    cancelEyebrow: "Cancelar tu cita",
    currentBooking: "Tu cita actual",
    language: "Idioma",
    chooseService: "Reserva una cita",
    chooseServiceSub: "Elige un servicio y verás los horarios disponibles en tu zona.",
    noServices: "No hay citas disponibles por el momento.",
    close: "Cerrar",
  },
  en: {
    allServices: "All services",
    minutes: (n: number) => `${n} min`,
    location: { in_person: "In person", phone: "Phone call", video: "Video call", custom: "Other location" } as Record<string, string>,
    yourZone: "Your time zone",
    detected: "Detected on your device.",
    chosen: "Chosen by you.",
    bizZone: (name: string, label: string) => `${name} works in ${label} time.`,
    searchZone: "Search for a city or time zone",
    zoneGroupMine: "Your time zone",
    allZones: (n: number) => `All time zones · ${n}`,
    noResults: "No results",
    confirmed: "Booking confirmed",
    sameInBiz: (name: string) => `The same time for ${name}:`,
    emailSent: "We've emailed you the details, with links to change or cancel it.",
    rescheduleEyebrow: "Change your booking",
    cancelEyebrow: "Cancel your booking",
    currentBooking: "Your current booking",
    language: "Language",
    chooseService: "Book an appointment",
    chooseServiceSub: "Pick a service to see the available times in your time zone.",
    noServices: "There are no appointments available right now.",
    close: "Close",
  },
} satisfies Record<Lang, unknown>;

export type Texts = (typeof T)["es"];

export const asLang = (v: string | null | undefined): Lang => (v?.toLowerCase().startsWith("en") ? "en" : "es");

/**
 * Textos del componente de Nylas que se sustituyen por la vía oficial (`localization`).
 * El español de Nylas mezcla tú y usted, habla de «reunión» y tiene un título en francés.
 * Ojo: el componente añade «!» detrás de `bookingConfirmed` y `bookingRescheduled`.
 */
export const NYLAS_TEXTS: Record<Lang, Record<string, string>> = {
  es: {
    noDateSelected: "Elige un día",
    rescheduleTitle: "Elige otro día y hora para tu cita.",
    nextButton: "Siguiente",
    backButton: "Atrás",
    namePlaceholder: "Tu nombre",
    emailPlaceholder: "tu@correo.com",
    bookNowButton: "Confirmar cita",
    bookingConfirmed: "¡Cita confirmada",
    bookingConfirmedDescription: "Te llegará un correo de confirmación en unos minutos.",
    bookingSent: "¡Solicitud enviada",
    bookingSentDescription: "Te escribiremos en cuanto se confirme la cita.",
    bookingRescheduled: "¡Cita cambiada",
    bookingDateAndTimeHeader: "Fecha y hora",
    cancelBookingButton: "Cancelar cita",
    rescheduleBookingButton: "Cambiar hora",
    bookingPendingTitle: "Cita pendiente",
    confirmedEventCardTitle: "Tu cita está confirmada",
    confirmedEventCardDescription: "Hemos enviado la confirmación a",
    cancelBookingTitle: "¿Cancelar la cita?",
    cancelBookingMessage: "Tu hora quedará libre para otras personas.",
    reasonForCancellation: "Motivo de la cancelación",
    goBackButton: "Volver",
    bookingCancelledTitle: "Cita cancelada",
    bookingCancelledMessage: "Hemos enviado la cancelación por correo a",
    bookingCancelledMessage_theParticipants: "los participantes",
    fieldRequired: "{{field}} es obligatorio.",
    invalidInputFormat: "{{field}} no tiene un formato válido.",
    createBookingErrorTitle: "No se pudo reservar",
    getAvailabilityErrorTitle: "No se pudieron cargar los horarios",
    cancelBookingErrorTitle: "No se pudo cancelar",
    rescheduleBookingErrorTitle: "No se pudo cambiar la cita",
    getUISettingErrorTitle: "No se pudo cargar el calendario",
    genericErrorTitle: "Algo ha fallado",
    invalidTimeslotErrorTitle: "Esa hora ya no está disponible",
    invalidTimeslotErrorMessage: "Elige otra hora, por favor.",
    cancellationErrorTitle: "No se pudo cancelar",
    cancellationErrorMessage: "Indica el motivo de la cancelación.",
    minimumCancellationErrorMessage: "No se puede cancelar con menos de {{minCancellationNotice}} minutos de antelación.",
  },
  en: {
    noDateSelected: "Pick a day",
    rescheduleTitle: "Pick a new day and time for your booking.",
    bookNowButton: "Confirm booking",
    bookingConfirmed: "Booking confirmed",
    bookingRescheduled: "Booking changed",
    cancelBookingButton: "Cancel booking",
    rescheduleBookingButton: "Change time",
    cancelBookingTitle: "Cancel this booking?",
    cancelBookingMessage: "Your time slot will be released for others.",
    reasonForCancellation: "Reason for cancelling",
    goBackButton: "Back",
  },
};
